Declare version 1.8.0
Cray-HPE/cf-gitea-import pull request #62
Opened 2023-01-19 22:19 UTC by jesseviola-hpe

## Summary and Scope

- Reverted build images to Jenkins from github workflows
- Delcare version 1.8.0 in Changelog
- Fixed copy directory library to silently fail and continue
- Adding new entrypoint for argo work

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves [CASMINST-5816](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5816)

## Pull Request Checklist

- [ ] Target branch correct
- [ ] Testing is appropriate and complete, if applicable
- [ ] Is a new version being released? Update https://github.com/Cray-HPE/cf-gitea-import/wiki/CSM-Compatibility-Matrix
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2023-01-19 22:27 UTC, ekamin-hpe submitted a review, later dismissed
LGTM. Not sure if my approval will count towards the requirement, but approving anyway.

2023-01-19 23:15 UTC, mharding-hpe approved these changes
The copyright years need to be updated in the files. I added suggestions for the ones I could, but some didn't have edits close enough to allow me to do it

2023-01-19 23:15 UTC, mharding-hpe commented on Jenkinsfile.github
> + *  (C) Copyright 2021-2022 Hewlett Packard Enterprise Development LP
```suggestion
 *  (C) Copyright 2021-2023 Hewlett Packard Enterprise Development LP
```

2023-01-19 23:15 UTC, mharding-hpe commented on Makefile
> +# (C) Copyright 2021-2022 Hewlett Packard Enterprise Development LP
```suggestion
# (C) Copyright 2021-2023 Hewlett Packard Enterprise Development LP
```

2023-01-19 23:15 UTC, mharding-hpe commented on argo_entrypoint.sh
> +# (C) Copyright 2020-2022 Hewlett Packard Enterprise Development LP
```suggestion
# (C) Copyright 2020-2023 Hewlett Packard Enterprise Development LP
```

2023-01-19 23:15 UTC, mharding-hpe commented on test/test_force_existing_branch.sh
> +# (C) Copyright 2021-2022 Hewlett Packard Enterprise Development LP
```suggestion
# (C) Copyright 2021-2023 Hewlett Packard Enterprise Development LP
```

2023-01-19 23:54 UTC, ekamin-hpe submitted a review, later dismissed

2023-01-19 23:55 UTC, haasken-hpe submitted a review, later dismissed

2023-01-20 12:48 UTC, mharding-hpe submitted a review, later dismissed

2023-01-20 12:48 UTC, mharding-hpe commented
> LGTM. Not sure if my approval will count towards the requirement, but approving anyway.

Your approval counts double!

2023-01-20 14:14 UTC, jsollom-hpe requested changes
This needs changes for Artifactory authentication.

2023-01-20 14:14 UTC, jsollom-hpe commented on CHANGELOG.md
> +## [Unreleased]
You can delete the [Unreleased] section on your release branch.

2023-01-20 14:14 UTC, jsollom-hpe commented on Jenkinsfile.github
> +                sh "make runbuildprep"
This is going to need the change to authenticate to artifactory if cms-meta-tools is going to succeed.

2023-01-20 14:21 UTC, jsollom-hpe commented on CHANGELOG.md
> +## [Unreleased]
I removed it myself as github gave me the option to commit to your PR.

2023-01-20 14:22 UTC, jsollom-hpe commented on Jenkinsfile.github
> +                sh "make runbuildprep"
I went ahead and made the authentication change and committed it to your PR. I am not sure about the etiquette of that maneuver. I would have put it in as a suggested fix, but I didn't see that option when I went to edit the file. In this case, I didn't think you'd mind, but in general I'm not in the habit of committing additional changes to people's PRs without their consent.

2023-01-20 14:24 UTC, jsollom-hpe approved these changes
My approval is conditional on the rebuild succeeding. I triggered one this morning after making a change to do artifactory authentication.

2023-01-20 14:24 UTC, rbak-hpe approved these changes

2023-01-20 17:08 UTC, merged