CASM-4231 Enhanced Logging for IUF Scripts
Cray-HPE/cf-gitea-import pull request #84
Opened 2023-05-18 09:27 UTC by rajeshranganathan-hpe

## Summary and Scope

This change is to support enhanced logging for scripts used by IUF operations. The "argo_entrypoint.sh" script is used by the "vcs-upload" operation of the "deliver-product" stage of IUF. The changes introduce log levels to each statement that logs information for user. 
## Issues and Related PRs
None

## Testing

Planned for test in #gamora.

### Tested on:

  * `gamora`

### Test description:

Run the "deliver-product" stage for the "COS" product to verify.

## Risks and Mitigations

None

## Pull Request Checklist

- [x] Target branch correct
- [ ] Testing is appropriate and complete, if applicable
- [ ] Is a new version being released? Update https://github.com/Cray-HPE/cf-gitea-import/wiki/CSM-Compatibility-Matrix
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2023-05-18 20:41 UTC, JohnNavitskyHPE commented on argo_entrypoint.sh
> +echo "INFO Gitea API available";
debug

2023-05-18 20:42 UTC, JohnNavitskyHPE commented on argo_entrypoint.sh
> +  echo "INFO Waiting for 3 seconds for Gitea API to be available"; \
debug

2023-05-19 17:58 UTC, JohnNavitskyHPE approved these changes

2023-05-31 16:03 UTC, mharding-hpe commented on argo_entrypoint.sh
> +  echo "DEBUG Waiting for 3 seconds for Gitea API to be available"; \
```suggestion
  echo "DEBUG: Waiting for 3 seconds for Gitea API to be available"; \
```

2023-05-31 16:04 UTC, mharding-hpe commented on argo_entrypoint.sh
> +echo "DEBUG Gitea API available";
```suggestion
echo "DEBUG: Gitea API available";
```

2023-05-31 16:05 UTC, mharding-hpe commented on argo_entrypoint.sh
> +cp -r "/shared/"* ${CF_IMPORT_CONTENT}/ && echo "INFO overwriting /content success" || echo "ERROR overwriting /content failed"
```suggestion
cp -rv "/shared/"* "${CF_IMPORT_CONTENT}/" && echo "INFO: overwriting /content success" || echo "ERROR: overwriting /content failed"
```

2023-05-31 16:05 UTC, mharding-hpe commented on argo_entrypoint.sh
> +echo "DEBUG Starting to import the contents of the ${CF_IMPORT_CONTENT} directory into Gitea"
```suggestion
echo "DEBUG: Starting to import the contents of the ${CF_IMPORT_CONTENT} directory into Gitea"
```

2023-05-31 16:08 UTC, mharding-hpe requested changes
Why are some of the logging levels in the Python script changed from info to debug? That means they will show up less often. Is that desired? The PR sounds like it is trying to increase the amount of logging, but that would decrease it. Is that intended?

2023-05-31 20:37 UTC, mharding-hpe approved these changes

2023-05-31 20:39 UTC, merged

2023-06-01 23:00 UTC, JohnNavitskyHPE commented
> Why are some of the logging levels in the Python script changed from info to debug? That means they will show up less often. Is that desired? The PR sounds like it is trying to increase the amount of logging, but that would decrease it. Is that intended?

so the overall tone that was attempted (across all the operations) were things like:
* don't tell the user you are about to do something, then tell them you did it if those operations are in close succession.  move the "i am about to do something" into debug since it may be useful if there is a problem since it helps identify which area of code you're in, but instead, focus on printing an info or error about the RESULT of that operation.  
* move stuff that's basically internal housekeeping stuff to debug.   so for example, don't tell them you checked out a copy of the repo, just tell them that you imported branch xyz or you merged branch foo into bar.  since we moved the other messages to debug, if there's an actual problem they need to debug, the information is still there but the flow of the output to the command line is much easier to follow.